version: 0.2

phases:
  install:
    # runtime-versions:
    #   docker: 18
    #   java: openjdk11
    commands:
      - echo install - begin
      # - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
      # - apt-get update
      # - apt-get upgrade -y
    finally:
      - echo install phase complete!

  pre_build:
    commands:
      - echo Logging in to Amazon ECR... 
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - ECR=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

  build:
    commands:
      - echo Build started
      - docker build -t $APP:$TARGET --build-arg source=$source --build-arg destination=$destination .
      - echo Build done

  post_build:
    commands:
      - docker tag $APP:$TARGET $COPY3S_ECR:$TARGET
      - docker push $COPY3S_ECR:$TARGET
